apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: eddie-register-app-deployment
  spec:
    replicas: 1
images:
- name: eddiebyte/eddie-register-app
  newName: eddiebyte/eddie-register-app
  newTag: 1.0.0-9
